### ISSUE TITLE
Error installing the latest version of dynet

### ISSUE THREAD

**Issue by philip30** [clab/dynet#1507]
I've been trying installing the latest version of dynet, but got an error when following the installation from the documentation using pip. I've been trying also installing manually but got the same error.

Maybe it is an error specific to my environment?

```
[  9%] Building NVCC intermediate link file dynet/CMakeFiles/dynet.dir/dynet_intermediate_link.o
    Scanning dependencies of target dynet
    [ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
    [ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
    [ 13%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
    [ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
    [ 16%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
    [ 17%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
    [ 18%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
    [ 20%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
    [ 21%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
    [ 22%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
    [ 24%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
    [ 25%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
    [ 26%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o
    [ 28%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o
    [ 29%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o
    [ 30%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o
    [ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/io.cc.o
    [ 33%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o
    [ 34%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
    [ 36%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o
    [ 37%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-activations.cc.o
    [ 38%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o
    [ 40%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-argmax.cc.o
    [ 41%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-const.cc.o
    [ 42%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-cwise.cc.o
    [ 44%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-sum.cc.o
    /tmp/pip-install-6ryc7on6/dynet/dynet/expr.cc: In function ‘dynet::Expression dynet::strided_select(const dynet::Expression&, const std::vector<int>&, const std::vector<int>&, const std::vector<int>&)’:
    /tmp/pip-install-6ryc7on6/dynet/dynet/expr.cc:201:74: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for(unsigned d=0;d<range_to.size() && d<x.dim().nd;d++){ if(range_to[d]!=x.dim()[d]) inplaced = false; }
                                                                              ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/lstm.cc: In member function ‘void dynet::SparseLSTMBuilder::set_sparsity(float)’:
    /tmp/pip-install-6ryc7on6/dynet/dynet/lstm.cc:686:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0;i<layers;i++){
                       ^
    [ 45%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-unary.cc.o
    [ 46%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-concat.cc.o
    [ 48%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-const.cc.o
    [ 49%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-contract.cc.o
    [ 50%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv.cc.o
    [ 52%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv2d.cc.o
    [ 53%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-dropout.cc.o
    [ 54%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-flow.cc.o
    [ 56%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-hinge.cc.o
    [ 57%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-linalg.cc.o
    [ 58%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-losses.cc.o
    [ 60%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-logsumexp.cc.o
    [ 61%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-lstm.cc.o
    [ 62%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-matrixmultiply.cc.o
    [ 64%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-maxpooling2d.cc.o
    [ 65%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-minmax.cc.o
    [ 66%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-moments.cc.o
    [ 68%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-cumulative.cc.o
    [ 69%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-normalization.cc.o
    [ 70%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-norms.cc.o
    [ 72%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-pickneglogsoftmax.cc.o
    [ 73%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-random.cc.o
    [ 74%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-rounding.cc.o
    [ 76%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-select.cc.o
    [ 77%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-similarities.cc.o
    [ 78%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-softmaxes.cc.o
    [ 80%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-to-device.cc.o
    [ 81%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-trig.cc.o
    [ 82%] Building CXX object dynet/CMakeFiles/dynet.dir/param-init.cc.o
    [ 84%] Building CXX object dynet/CMakeFiles/dynet.dir/param-nodes.cc.o
    [ 85%] Building CXX object dynet/CMakeFiles/dynet.dir/pretrain.cc.o
    [ 86%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn-state-machine.cc.o
    In file included from /tmp/pip-install-6ryc7on6/dynet/dynet/dim.h:18:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/tensor.h:15,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/tensor-eigen.h:8,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc:1:
    /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc: In member function ‘virtual dynet::Dim dynet::StridedSelect::dim_forward(const std::vector<dynet::Dim>&) const’:
    /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc:379:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           DYNET_ARG_CHECK(from[d] < xs[0].d[d] && from[d] >= 0, "require 0 <= from < dim_size, was " << from[d]);
                                   ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/except.h:42:11: note: in definition of macro ‘DYNET_ARG_CHECK’
         if (!(cond)) {                                \
               ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc:381:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           DYNET_ARG_CHECK(from[d] < xs[0].bd && from[d] >= 0, "require 0 <= from < batch_size, was " << from[d]);
                                   ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/except.h:42:11: note: in definition of macro ‘DYNET_ARG_CHECK’
         if (!(cond)) {                                \
               ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc:386:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           DYNET_ARG_CHECK(to[d] <= xs[0].d[d] && to[d] > 0, "require 0 < to <= dim_size, was " << to[d]);
                                 ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/except.h:42:11: note: in definition of macro ‘DYNET_ARG_CHECK’
         if (!(cond)) {                                \
               ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/nodes-select.cc:388:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           DYNET_ARG_CHECK(to[d] <= xs[0].bd && to[d] > 0, "require 0 < to <= batch_size, was " << to[d]);
                                 ^
    /tmp/pip-install-6ryc7on6/dynet/dynet/except.h:42:11: note: in definition of macro ‘DYNET_ARG_CHECK’
         if (!(cond)) {                                \
               ^
    [ 88%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn.cc.o
    [ 89%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o
    [ 90%] Building CXX object dynet/CMakeFiles/dynet.dir/shadow-params.cc.o
    [ 92%] Building CXX object dynet/CMakeFiles/dynet.dir/tensor.cc.o
    [ 93%] Building CXX object dynet/CMakeFiles/dynet.dir/training.cc.o
    [ 94%] Building CXX object dynet/CMakeFiles/dynet.dir/treelstm.cc.o
    [ 96%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o
    [ 97%] Building CXX object dynet/CMakeFiles/dynet.dir/cuda.cc.o
    /tmp/pip-install-6ryc7on6/dynet/dynet/treelstm.cc: In member function ‘virtual dynet::Expression dynet::BidirectionalTreeLSTMBuilder::add_input(int, std::vector<int>, const dynet::Expression&)’:
    /tmp/pip-install-6ryc7on6/dynet/dynet/treelstm.cc:375:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (h.size() == id)
                    ^
    [ 98%] Linking CXX shared library libdynet.so
    [ 98%] Built target dynet
    Scanning dependencies of target pydynet_precopy
    [ 98%] Built target pydynet_precopy
    Scanning dependencies of target pydynet
    [100%] Generating timestamp
    running build_ext
    INFO:root:Building Cython extensions...
    INFO:root:INCLUDE_DIRS='/tmp/pip-install-6ryc7on6/dynet /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen'
    INFO:root:LIBRARIES='dynet cublas'
    INFO:root:LIBRARY_DIRS='/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/dynet/ . /usr/local/cuda/9.1/lib64'
    INFO:root:COMPILER_ARGS='-std=c++11 -Wno-unused-function'
    INFO:root:EXTRA_LINK_ARGS="-Wl,-rpath='/home/philipa/.pyenv/versions/3.6.0/lib/',--no-as-needed"
    INFO:root:RUNTIME_LIB_DIRS='/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/dynet/ /home/philipa/.pyenv/versions/3.6.0/lib/'
    cythoning /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.pyx to /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp
    building '_dynet' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/tmp
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6/dynet
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6/dynet/build
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/pytho
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/boost/1.67.0-gcc5/include -I/usr/local/java/jdk1.8.0_77/include -I/usr/local/protobuf/master/include -I/usr/local/boost/1.67.0-gcc5/include -I/usr/local/hdf5/1.10.0-patch1/include -I/usr/local/eigen/3.3.0/include -I/usr/local/cuda/9.1/include/CL -I/usr/local/cuda/9.1/include -I/usr/local/gcc/5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/ -I/usr/local/gcc/5.4.0/include -I/usr/local/bzip2/1.0.6/include -fPIC -I/tmp/pip-install-6ryc7on6/dynet -I/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen -I/home/philipa/.pyenv/versions/3.6.0/include/python3.6m -c /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp -o build/temp.linux-x86_64-3.6/tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.o -std=c++11 -Wno-unused-function
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/Tensor:100:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/index-tensor.h:10,
                     from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp:591:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorIndexList.h:220:10: error: ‘array_size’ is not a class template
       struct array_size<IndexTuple<T, O...> > {
              ^
    In file included from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/Tensor:110:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/index-tensor.h:10,
                     from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp:591:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:189:50: error: ‘scalar_expm1_op’ is not a member of ‘Eigen::internal’
         EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived>
                                                      ^
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:189:50: error: ‘scalar_expm1_op’ is not a member of ‘Eigen::internal’
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:189:82: error: wrong number of template arguments (1, should be 2)
         EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived>
                                                                                      ^
    In file included from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/Tensor:92:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/index-tensor.h:10,
                     from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp:591:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorForwardDeclarations.h:60:52: note: provided for ‘template<class UnaryOp, class XprType> class Eigen::TensorCwiseUnaryOp’
     template<typename UnaryOp, typename XprType> class TensorCwiseUnaryOp;
                                                        ^
    In file included from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/Tensor:110:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/index-tensor.h:10,
                     from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp:591:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:189:83: error: expected unqualified-id before ‘,’ token
         EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived>
                                                                                       ^
    In file included from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/Tensor:150:0,
                     from /tmp/pip-install-6ryc7on6/dynet/dynet/index-tensor.h:10,
                     from /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/python/_dynet.cpp:591:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h: In member function ‘void Eigen::TensorStorage<T, Eigen::DSizes<IndexType, NumIndices_>, Options_>::resize(Eigen::TensorStorage<T, Eigen::DSizes<IndexType, NumIndices_>, Options_>::Index, Eigen::array<IndexType, NumIndices_>&)’:
    /tmp/pip-install-6ryc7on6/dynet/build/py3.6-64bit/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:130:7: error: expected ‘;’ before ‘}’ token
           }
           ^
    error: command 'gcc' failed with exit status 1
    make[2]: *** [python/timestamp] Error 1
    make[1]: *** [python/CMakeFiles/pydynet.dir/all] Error 2
    make: *** [all] Error 2
    error: /bin/make -j 24

    ----------------------------------------
Command "/home/philipa/.pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6ryc7on6/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cq91sbhn/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6ryc7on6/dynet/

```

**Comment by philip30** [comment]
This is a clean build btw.

**Comment by philip30** [comment]
I tried with a higher version of GCC and it works. Not sure why. I was failing to build with GCC 5.4.0. Maybe I want to close this issue for now.
