### ISSUE TITLE
node unit testing reports failure in cudnn operation

### ISSUE THREAD

**Issue by mattr1** [clab/dynet#1150]
test-nodes reports

C:/gits/dynet/tests/test-nodes.cc(1674): error: in "node_test/conv2d_valid_singlefilter_gradient": check check_grad(mod, z, 0) has failed

@redpony: I've narrowed it down to being caused by commit 84ca496ab41077289a502589c116c7be81a1bfb7 (which I see caused some other testing errors that you needed to fix). This one probably wasn't caught because testing is not being done on the cudnn code by default (?). I wasn't sure what it was about the changes you made that fixed the unit testing, can you suggest a change for the cudnn failure (I can test it out for you if that's more convenient for you).

Note that you will be unable to compile the cudnn code until PR #1149 is accepted.

**Comment by redpony** [comment]
This was temporarily broken, but I think
https://github.com/clab/dynet/commit/9b50b354c3cb66a4163c879ecaa689741a2a6017
should have fixed it.

**Comment by mattr1** [comment]
I saw that checkin, which I presumed fixed some other problems too, but unfortunately it didn't fix the cudnn error for me. In fact, the cudnn code didn't even compile. Are you running with -DCUDNN_ROOT defined?

**Comment by redpony** [comment]
Oh sorry, yes, that was CPU only (basically there are some numerical
stability issues). I'll look into this. But this was a bug fix for tests,
so I thought a few broken tests were better to have in master than the
appearance that everything was healthy. I'll be able to look into the
failures with cudnn early next week.

**Comment by mattr1** [comment]
Great, thanks! I definitely agree that some errors in the tests are low priority.
